name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          #- distribution: fedora
          - distribution: alpine
          - distribution: ubuntu

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Test using Docker
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: test/Dockerfile-${{ matrix.distribution }}
          push: false
